# Generated by Django 4.0.2 on 2022-02-19 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_subscribedcoursedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedcoursedetails',
            name='subscribedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 22, 42, 43, 694536)),
        ),
    ]
