# Generated by Django 4.0.1 on 2022-02-19 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_subscribedcoursedetails_subscribedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedcoursedetails',
            name='subscribedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 23, 23, 35, 842983)),
        ),
    ]
