# Generated by Django 4.0.2 on 2022-02-19 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=20)),
                ('courseName', models.CharField(max_length=250)),
                ('courseDescription', models.TextField()),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 2, 19, 20, 52, 11, 837671))),
                ('status', models.BooleanField(default=True)),
                ('courseDuration', models.CharField(max_length=20)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitName', models.CharField(max_length=250)),
                ('unitDescription', models.TextField()),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 2, 19, 20, 52, 11, 838668))),
                ('status', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.courses')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=250)),
                ('topicDescription', models.TextField()),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 2, 19, 20, 52, 11, 838668))),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.units')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopicContent', models.TextField()),
                ('contentType', models.CharField(max_length=10)),
                ('updatedOn', models.DateTimeField()),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 2, 19, 20, 52, 11, 838668))),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.subtopics')),
            ],
        ),
    ]
